### ISSUE TITLE
Enable mapping of TA to another value

### ISSUE THREAD

**Issue by natdudley** [WikiNewZealand/fundamental-figures#20]
Some datasets are about a TA, but use a different classification.

For example, the local election stats are technically for the government body, e.g. Hamilton City Council, rather than the Hamilton TA.

https://figure.nz/table/T2Pky1MavryS2xzy

Another example is region, where data for the Waikato region is useful for Hamilton.

**Comment by natdudley** [comment]
Council Datasets

https://figure.nz/table/CV2WlAfOYtAhx3jO
https://figure.nz/table/T2Pky1MavryS2xzy
https://figure.nz/table/awE6B0Siz3kPENiS
https://figure.nz/table/S2LNiW2acMml59MK
https://figure.nz/table/BDbwxnnEA5khmkwC
https://figure.nz/table/deetNqyR2dBOp6WS

These ones are quite important because they include local election stats and council finance stats

**Comment by natdudley** [comment]
This is an interesting one

https://figure.nz/table/BDbwxnnEA5khmkwC

It has TA figures, regional countil figures, and things liek Auckland Transport.

**Comment by natdudley** [comment]
There's shit-tons of region data, and it's definitely the big outstanding section (but can wait until after website, most def). It's of interest because it's also elections for regional councils.

**Comment by natdudley** [comment]
DHBs have maybe 15-20 datasets. There is no variation in DHBs listed, but each DHB will need to be mapped to one or more TAs.

Correspondingly, when you select a TA with more than one DHB associated (like Auckland, we'll need facility to say "+ this DHB, or to filter when you get to health results section.

**Comment by Spksh** [comment]
See readme.md
