### ISSUE TITLE
website/json is incorrectly generating some dates

### ISSUE THREAD

**Issue by natdudley** [WikiNewZealand/fundamental-figures#24]
First dataset in demographics should have

Estimated population year 2016
Low, medium, high population year 2043

https://figure.nz/table/xZOqU5b6uSVVMPiD

It is correct in the excel sheet.

**Comment by Spksh** [comment]
Breaking change in JSON schema, requires corresponding change in find-your-place.

**Comment by Spksh** [comment]
Regenerated all output files and updated find-your-place to match changed schema.
