### ISSUE TITLE
generate mapping files for government-ta and dhb-ta

### ISSUE THREAD

**Issue by natdudley** [WikiNewZealand/fundamental-figures#30]
Using files in Dropbox, generate a mapping for government to ta, and dhb to ta, please.

**Comment by natdudley** [comment]
Oh, and RTO-TA

**Comment by Spksh** [comment]
Fixed in 6c956aa5c444d461ee962089e33d60bb2bab40f8 and 656f78bb7fc39fffbcde7a4b4798b24736a1418d
